title: Problem Package Format
repository: Kattis/problem-package-format
lang: en
description: Problem Package Format Specification

readme_index:
  with_frontmatter: true

theme: null

# https://jv-conseil.github.io/jekyll-theme-read-the-docs/
remote_theme: JV-conseil/jekyll-theme-read-the-docs

# if this breaks too here's an alternative
# https://github.com/just-the-docs/just-the-docs
# remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-remote-theme

markdown: CommonMarkGhPages
commonmark:
  # Unsafe allows passthrough of <div class="not-icpc">
  options: ["SMART", "UNSAFE"]
  extensions: ["table"]
